// Tests for apps-script/Code.gs with fake Google services (contracts/apps-script.md).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { loadGs, plain } from './load-gs.mjs';
import { createFakes } from './fakes.mjs';

const SPREADSHEET_ID = 'sheet-123';

function setup({ log = [['Date', 'Drill', 'W', 'R']], workout = [['date', 'duration, min', 'work alone']], money = [['date', 'workouts', 'sum']] } = {}) {
  const fakes = createFakes();
  const ss = fakes.useSpreadsheet(new fakes.FakeSpreadsheet([
    new fakes.FakeSheet('log', log),
    new fakes.FakeSheet('drills', [['mscl', 'drill']]),
    new fakes.FakeSheet('rec', [['', '', '', 'FILTER(log!A:Z, log!B:B=A1)']]),
    new fakes.FakeSheet('money', money),
    new fakes.FakeSheet('workout', workout),
    new fakes.FakeSheet('balance', [[0]]),
  ]));
  // Config.gs is generated by the app at upload time; the test stub declares the same constants.
  const ctx = loadGs(['Logic.gs', 'Code.gs'], {
    ...fakes.globals,
    SPREADSHEET_ID,
    SCRIPT_VERSION: 1,
  });
  return { fakes, ss, ctx };
}

const editEvent = (ss, sheetName, row, col, value) => ({
  source: ss,
  value,
  range: {
    rowStart: row,
    columnStart: col,
    getSheet: () => ss.getSheetByName(sheetName),
    getRow: () => row,
    getColumn: () => col,
    getValue: () => ss.getSheetByName(sheetName).cell(row, col),
  },
});

test('onEdit ignores other tabs', () => {
  const { ss, ctx, fakes } = setup();
  ctx.onEdit(editEvent(ss, 'money', 3, 2, '10'));
  assert.equal(fakes.calls.length, 0);
});

test('onEdit ignores other columns of log', () => {
  const { ss, ctx, fakes } = setup();
  ctx.onEdit(editEvent(ss, 'log', 3, 3, '20'));
  assert.equal(fakes.calls.length, 0);
});

test('onEdit on log column B fills empty rows above, dates where empty, and sets rec!A1', () => {
  const stamp = new Date('2026-01-01T08:00:00Z');
  const { ss, ctx } = setup({
    log: [
      ['Date', 'Drill', 'W', 'R'],
      [stamp, 'жим', 20, 10],
      ['', '', 25, 8],
      ['', '', 25, 8],
      ['', 'тяга', 30, 6],
    ],
  });
  ctx.onEdit(editEvent(ss, 'log', 5, 2, 'тяга'));
  const log = ss.getSheetByName('log');
  assert.equal(log.cell(3, 2), 'тяга');
  assert.equal(log.cell(4, 2), 'тяга');
  assert.equal(log.cell(2, 2), 'жим', 'stops at the first filled row');
  for (const row of [3, 4, 5]) assert.ok(log.cell(row, 1) instanceof Date, `row ${row} gets a date-time`);
  assert.equal(log.cell(2, 1), stamp, 'existing dates are kept');
  assert.equal(ss.getSheetByName('rec').cell(1, 1), 'тяга');
});

test('onEdit ignores multi-cell edits and deletions (no value)', () => {
  const { ss, ctx, fakes } = setup();
  ctx.onEdit(editEvent(ss, 'log', 3, 2, undefined));
  assert.equal(fakes.calls.length, 0);
});

test('simple triggers never call SpreadsheetApp.openById', () => {
  const { ss, ctx, fakes } = setup({ log: [['Date', 'Drill', 'W', 'R'], ['', 'жим', 1, 1]] });
  ctx.onEdit(editEvent(ss, 'log', 2, 2, 'жим'));
  ctx.onSelectionChange(editEvent(ss, 'log', 2, 2));
  assert.deepEqual(fakes.openByIdCalls, []);
});

test('onSelectionChange on log column B sets rec!A1 to the selected exercise', () => {
  const { ss, ctx } = setup({ log: [['Date', 'Drill', 'W', 'R'], ['', 'присед', 60, 5]] });
  ctx.onSelectionChange(editEvent(ss, 'log', 2, 2));
  assert.equal(ss.getSheetByName('rec').cell(1, 1), 'присед');
});

test('onSelectionChange ignores the header row, empty cells and other columns', () => {
  const { ss, ctx, fakes } = setup({ log: [['Date', 'Drill', 'W', 'R'], ['', '', 60, 5]] });
  ctx.onSelectionChange(editEvent(ss, 'log', 1, 2));
  ctx.onSelectionChange(editEvent(ss, 'log', 2, 2));
  ctx.onSelectionChange(editEvent(ss, 'log', 2, 3));
  assert.equal(fakes.calls.length, 0);
});

test('doGet installs the daily trigger once and records enabling', () => {
  const { ss, ctx, fakes } = setup();
  ctx.doGet({ parameter: { lang: 'en' } });
  ctx.doGet({ parameter: { lang: 'en' } });
  const created = fakes.calls.filter((c) => c[0] === 'createTrigger').map((c) => c[1]);
  assert.deepEqual(plain(created), [{ handler: 'dailyJob', timeBased: true, everyDays: 1, atHour: 3 }]);
  assert.match(ss.metadataValue('workout_rec.automation_enabled_at'), /^\d{4}-\d\d-\d\dT/);
  assert.equal(ss.metadata.filter((m) => m.key === 'workout_rec.automation_enabled_at').length, 1, 'one entry per key');
  assert.deepEqual(fakes.openByIdCalls, [SPREADSHEET_ID, SPREADSHEET_ID]);
});

test('doGet renders the Enable page in Russian or English', () => {
  const { ctx } = setup();
  const ru = ctx.doGet({ parameter: { lang: 'ru' } });
  const en = ctx.doGet({ parameter: {} });
  assert.equal(ru.template.file, 'Enable');
  assert.equal(ru.template.lang, 'ru');
  assert.match(ru.title, /[А-Яа-я]/);
  assert.equal(en.template.lang, 'en');
  assert.match(en.title, /automation/i);
});

test('dailyJob appends three-value workout rows, then balance, then last run (in order)', () => {
  const { ss, ctx, fakes } = setup({
    log: [
      ['Date', 'Drill', 'W', 'R'],
      [new Date('2026-01-12T10:00:00Z'), 'жим', 20, 10],
      [new Date('2026-01-12T11:31:00Z'), 'тяга', 30, 8],
      [new Date('2026-01-14T09:00:00Z'), 'жим', 22, 10],
    ],
    workout: [
      ['date', 'duration, min', 'work alone'],
      [new Date('2026-01-12T00:00:00Z'), 91, 0],
    ],
    money: [['date', 'workouts', 'sum'], [new Date('2026-01-01T00:00:00Z'), 24, 24000]],
  });
  ctx.dailyJob();
  const kinds = fakes.calls.map((c) => c[0] === 'setValue' ? `setValue ${c[1]}` : c[0]);
  assert.deepEqual(kinds, ['appendRow', 'setValue balance!A1', 'addMetadata']);
  const appended = fakes.calls[0][2];
  assert.equal(appended.length, 3);
  assert.equal(appended[0].toISOString().slice(0, 10), '2026-01-14');
  assert.deepEqual(appended.slice(1), [0, 0]);
  assert.equal(ss.getSheetByName('balance').cell(1, 1), 22, '24 paid - 2 workouts');
  assert.ok(ss.metadataValue('workout_rec.last_daily_run'));
});

test('dailyJob updates last run instead of adding a second entry', () => {
  const { ss, ctx } = setup();
  ctx.dailyJob();
  ctx.dailyJob();
  assert.equal(ss.metadata.filter((m) => m.key === 'workout_rec.last_daily_run').length, 1);
});

test('logMetadata prints the markers and writes nothing', () => {
  const { ss, ctx, fakes } = setup();
  ss.metadata.push({ key: 'workout_rec.structure_version', value: '1', getKey() { return this.key; }, getValue() { return this.value; } });
  ctx.logMetadata();
  assert.deepEqual(fakes.logged, ['workout_rec.structure_version = 1']);
  assert.equal(fakes.calls.filter((c) => c[0] !== 'getDeveloperMetadata').length, 0);
});
