// Triggers and adapters between Logic.gs and the spreadsheet
// (contracts/apps-script.md). Tested with fakes in apps-script/tests/code.test.mjs.
//
// SPREADSHEET_ID and SCRIPT_VERSION come from Config.gs, generated by the app on upload.
//
// Simple triggers (onEdit, onSelectionChange) must use e.source / e.range only: they cannot
// call services that need authorization, such as SpreadsheetApp.openById. They therefore work
// before "Enable automation" is approved. doGet, dailyJob and logMetadata run authorized and
// open the spreadsheet by ID.

const LOG_SHEET = 'log';
const REC_SHEET = 'rec';
const DRILL_COLUMN = 2; // log column B
const DATE_COLUMN = 1; // log column A

const ENABLE_TEXTS = {
  en: {
    title: 'Workout Rec automation is on',
    body: 'Daily workouts and balance will now be updated automatically every night. You can close this page and return to the app.',
  },
  ru: {
    title: 'Автоматизация Workout Rec включена',
    body: 'Тренировки по дням и баланс теперь обновляются автоматически каждую ночь. Можно закрыть эту страницу и вернуться в приложение.',
  },
};

/** Auto-fill log rows (spec "Attached automation"). */
function onEdit(e) {
  const range = e.range;
  const sheet = range.getSheet();
  if (sheet.getName() !== LOG_SHEET || range.columnStart !== DRILL_COLUMN) return;
  const value = e.value;
  if (value === undefined || value === '') return; // multi-cell edit or deletion

  const row = range.rowStart;
  const now = new Date();
  const columnB = sheet.getRange(1, DRILL_COLUMN, row, 1).getValues().map(function (r) { return r[0]; });
  autoFillPlan(columnB, row).forEach(function (fillRow) {
    sheet.getRange(fillRow, DRILL_COLUMN).setValue(value);
    setIfEmpty_(sheet.getRange(fillRow, DATE_COLUMN), now);
  });
  setIfEmpty_(sheet.getRange(row, DATE_COLUMN), now);

  const rec = e.source.getSheetByName(REC_SHEET);
  if (rec) rec.getRange('A1').setValue(value);
}

/** Follow selection: show the selected exercise's history in rec. */
function onSelectionChange(e) {
  const range = e.range;
  const sheet = range.getSheet();
  if (sheet.getName() !== LOG_SHEET || range.getColumn() !== DRILL_COLUMN || range.getRow() < 2) return;
  const value = range.getValue();
  if (value === '' || value === null || value === undefined) return;
  const rec = e.source.getSheetByName(REC_SHEET);
  if (rec) rec.getRange('A1').setValue(value);
}

/** "Enable automation" page: installs the daily schedule once and records that it is on. */
function doGet(e) {
  const lang = e && e.parameter && e.parameter.lang === 'ru' ? 'ru' : 'en';
  const ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  const installed = ScriptApp.getProjectTriggers().some(function (t) {
    return t.getHandlerFunction() === 'dailyJob';
  });
  if (!installed) {
    ScriptApp.newTrigger('dailyJob').timeBased().everyDays(1).atHour(3).create();
  }
  setMetadata_(ss, 'workout_rec.automation_enabled_at', new Date().toISOString());

  const template = HtmlService.createTemplateFromFile('Enable');
  template.lang = lang;
  template.texts = ENABLE_TEXTS[lang];
  return template.evaluate().setTitle(ENABLE_TEXTS[lang].title);
}

/** Nightly: daily workouts first, then balance (so it includes the new rows), then a marker. */
function dailyJob() {
  const ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  const timeZone = ss.getSpreadsheetTimeZone();
  const toDayKey = function (date) { return Utilities.formatDate(date, timeZone, 'yyyy-MM-dd'); };

  const logRows = dataRows_(ss.getSheetByName(LOG_SHEET));
  const workoutSheet = ss.getSheetByName('workout');
  const existingDays = new Set(
    dataRows_(workoutSheet)
      .filter(function (r) { return r[0] instanceof Date; })
      .map(function (r) { return toDayKey(r[0]); })
  );
  dailyWorkoutRows(logRows, existingDays, toDayKey).forEach(function (row) {
    workoutSheet.appendRow(row);
  });

  const moneyWorkouts = dataRows_(ss.getSheetByName('money')).map(function (r) { return r[1]; });
  const aloneFlags = dataRows_(workoutSheet)
    .filter(function (r) { return r.join('') !== ''; })
    .map(function (r) { return r[2]; });
  ss.getSheetByName('balance').getRange('A1').setValue(balance(moneyWorkouts, aloneFlags));

  setMetadata_(ss, 'workout_rec.last_daily_run', new Date().toISOString());
}

/** Show status: print the app's status markers to the Execution log. Read-only. */
function logMetadata() {
  const ss = SpreadsheetApp.openById(SPREADSHEET_ID);
  const entries = ss.getDeveloperMetadata().map(function (m) {
    return { key: m.getKey(), value: m.getValue() };
  });
  console.log(formatMetadata(entries));
}

function setIfEmpty_(range, value) {
  if (range.getValue() === '') range.setValue(value);
}

/** All rows except the header. */
function dataRows_(sheet) {
  return sheet.getDataRange().getValues().slice(1);
}

/** Each key appears at most once (contracts/spreadsheet.md). */
function setMetadata_(ss, key, value) {
  const existing = ss.createDeveloperMetadataFinder().withKey(key).find();
  if (existing.length > 0) {
    existing[0].setValue(value);
  } else {
    ss.addDeveloperMetadata(key, value, SpreadsheetApp.DeveloperMetadataVisibility.DOCUMENT);
  }
}
