package com.workoutrec.automation

import android.content.res.AssetManager
import com.workoutrec.google.GoogleJson
import com.workoutrec.google.ScriptApi
import com.workoutrec.google.ScriptFile
import com.workoutrec.google.ScriptFileType
import com.workoutrec.google.SheetsApi
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/** Reads the bundled script files (assets/apps-script/). */
fun interface ScriptAssets {
    fun read(name: String): String

    companion object {
        fun from(assets: AssetManager) = ScriptAssets { name ->
            assets.open("apps-script/$name").bufferedReader().use { it.readText() }
        }
    }
}

data class InstalledScript(val scriptId: String, val enableUrl: String)

/** Attaches the script to the spreadsheet (research R8). */
interface ScriptInstall {
    suspend fun install(
        spreadsheetId: String,
        timeZone: String,
        existingMetadata: Map<String, String>,
        existingIds: Map<String, Int>,
    ): InstalledScript
}

class ScriptInstaller(
    private val script: ScriptApi,
    private val sheets: SheetsApi,
    private val assets: ScriptAssets,
) : ScriptInstall {

    /**
     * Creates the attached project (unless one is recorded), uploads the files, publishes the
     * "Enable automation" page, and records both in the spreadsheet's metadata. Throws
     * ApiError.AppsScriptApiDisabled when the user's Apps Script API setting is off (step 1).
     */
    override suspend fun install(
        spreadsheetId: String,
        timeZone: String,
        existingMetadata: Map<String, String>,
        existingIds: Map<String, Int>,
    ): InstalledScript {
        val existingScript = existingMetadata[AutomationStatusEvaluator.SCRIPT_ID]?.takeIf { it.isNotBlank() }
        val existingUrl = existingMetadata[AutomationStatusEvaluator.ENABLE_URL]?.takeIf { it.isNotBlank() }
        if (existingScript != null && existingUrl != null) return InstalledScript(existingScript, existingUrl)

        val scriptId = existingScript ?: script.createProject(title = PROJECT_TITLE, parentId = spreadsheetId)
        script.updateContent(scriptId, files(spreadsheetId, timeZone))
        val version = script.createVersion(scriptId, "workout_rec v$SCRIPT_VERSION")
        val url = script.deployWebApp(scriptId, version, description = "enable")
        sheets.upsertMetadata(
            spreadsheetId,
            linkedMapOf(AutomationStatusEvaluator.SCRIPT_ID to scriptId, AutomationStatusEvaluator.ENABLE_URL to url),
            existingIds,
        )
        return InstalledScript(scriptId, url)
    }

    private fun files(spreadsheetId: String, timeZone: String): List<ScriptFile> = listOf(
        ScriptFile("appsscript", ScriptFileType.JSON, manifest(timeZone)),
        ScriptFile("Config", ScriptFileType.SERVER_JS, config(spreadsheetId)),
        ScriptFile("Logic", ScriptFileType.SERVER_JS, assets.read("Logic.gs")),
        ScriptFile("Code", ScriptFileType.SERVER_JS, assets.read("Code.gs")),
        ScriptFile("Enable", ScriptFileType.HTML, assets.read("Enable.html")),
    )

    /** The bundled manifest with the spreadsheet's time zone, so the 03:00 trigger is local. */
    private fun manifest(timeZone: String): String {
        val manifest = GoogleJson.parseToJsonElement(assets.read("appsscript.json")) as JsonObject
        return JsonObject(manifest + ("timeZone" to JsonPrimitive(timeZone))).toString()
    }

    private fun config(spreadsheetId: String): String =
        "// Generated by the Workout Rec app. Do not edit.\n" +
            "const SPREADSHEET_ID = '${spreadsheetId.replace("'", "")}';\n" +
            "const SCRIPT_VERSION = $SCRIPT_VERSION;\n"

    companion object {
        const val PROJECT_TITLE = "workout_rec_automation"
        const val SCRIPT_VERSION = 1
    }
}
